<a href="https://colab.research.google.com/github/sdubee10/Embedded-System/blob/master/numpy_and_pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import numpy as np

In [ ]:
#list_name(변수명 설정) = ["item1", "item2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [ ]:
# append()로 리스트에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [ ]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [ ]:
# 배열(또는 행렬)을 1로 채우기
print(np.ones((1, 5)))
print(np.ones((3, 2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
# 배열(또는 행렬)을 0으로 채우기
print(np.zeros((1, 5)))
print(np.zeros((3, 2)))

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [19]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))

# 정규분포를 따르는 값 0~1사이
mat3 = np.random.rand(3,2)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[4 4]
 [9 2]
 [3 9]]
[[0.87398158 0.46908085]
 [0.20507425 0.99630077]
 [0.29315869 0.66808455]]


### 리스트 인덱싱(Indexing) & 슬라이싱(Slicing)




In [23]:
# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])

5 11 11


In [24]:
# Slicing
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


### numpy의 reshape (PyTorch의 view와 비교)

In [25]:
# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.85774838 0.73559784 0.90826659]
 [0.18167187 0.7168654  0.92309261]
 [0.19175737 0.61878048 0.02656579]
 [0.03720646 0.88948432 0.92307119]
 [0.99075624 0.65077466 0.48709199]
 [0.09044274 0.51014327 0.68185562]]


In [26]:
# -1: all
# -1 이 두번째에 들어가면 가로로 출력(열이 18개, 행이 1개)
print(mat1.reshape(1, -1).shape)
print(mat1.reshape(1, -1))
print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

(1, 18)
[[0.85774838 0.73559784 0.90826659 0.18167187 0.7168654  0.92309261
  0.19175737 0.61878048 0.02656579 0.03720646 0.88948432 0.92307119
  0.99075624 0.65077466 0.48709199 0.09044274 0.51014327 0.68185562]]
=====
(18, 1)
[[0.85774838]
 [0.73559784]
 [0.90826659]
 [0.18167187]
 [0.7168654 ]
 [0.92309261]
 [0.19175737]
 [0.61878048]
 [0.02656579]
 [0.03720646]
 [0.88948432]
 [0.92307119]
 [0.99075624]
 [0.65077466]
 [0.48709199]
 [0.09044274]
 [0.51014327]
 [0.68185562]]


In [30]:
print(mat1.reshape(2, 9).shape)
print("--------")
print(mat1.reshape(9, 2))

(2, 9)
--------
[[0.85774838 0.73559784]
 [0.90826659 0.18167187]
 [0.7168654  0.92309261]
 [0.19175737 0.61878048]
 [0.02656579 0.03720646]
 [0.88948432 0.92307119]
 [0.99075624 0.65077466]
 [0.48709199 0.09044274]
 [0.51014327 0.68185562]]


In [33]:
#에러가 발생하는 이유: 사이즈가 안맞기 때문
#mat1.reshape(2,5)

In [32]:
# tensor 형태로 나타내기
# tensor: 3차원 이상을 표현할 때
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.85774838 0.73559784 0.90826659]
  [0.18167187 0.7168654  0.92309261]]

 [[0.19175737 0.61878048 0.02656579]
  [0.03720646 0.88948432 0.92307119]]

 [[0.99075624 0.65077466 0.48709199]
  [0.09044274 0.51014327 0.68185562]]]


### matrix 또는 tensor 형태에서도 slicing이 가능합니다!

In [37]:
# 앞에 -1이 있으면, 가로로 4개씩 짜르겠다는 의미
mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
